typography_spectrum: 0.5614623526280912
color:
  brandStrength: 0.007365259669241633
  lightness: 0.17432716089411465
  saturation: 0.9251208338446657
  rhythmicContrast: 0.29955946322087895
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
github: true
layout_spectrum: 0.1334736367196103
analytics:
  twitter: '@evacrity'
  google: UA-97897450-1
author:
  name: Evacrity VR
  email: info@evacrity.com
  url: 'http://evacrity.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4aa17c84-62ae-47af-8ab8-e64ae3384819.png
name: Evacrity VR
url: 'http://evacrity.com/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Evacrity Twitch
    url: 'https://www.twitch.tv/scieVR'
    type: external
  - name: Evacrity Youtube Channel
    url: 'https://www.youtube.com/channel/UCif4DnRhmIxC9llo8TCzrPQ'
    type: external
  - name: Instagram
    url: 'https://www.instagram.com/evacrity_vr/'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/evacrityVR/?ref=aymt_homepage_panel'
    type: external
  - name: Evacrity Twitter
    url: 'https://twitter.com/'
    type: external
  - name: Blog
    url: 'http://evacrity.tumblr.com/'
    type: external
  - name: Patreon
    url: 'https://www.patreon.com/evacrity'
    type: external
  - name: Gab.ai
    url: 'https://gab.ai/evacrity'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/55993fb6-f8db-4184-925f-3dc04d164ca0.png
title: Evacrity VR - Gaming Meets Fitness
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/6d4998ac-3ff0-4a3d-a515-094864cd1235.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/6d4998ac-3ff0-4a3d-a515-094864cd1235.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/dda35690-df72-40b6-a1e8-0398a99f77c7.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/dda35690-df72-40b6-a1e8-0398a99f77c7.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'Physical, realistic and immersive VR gaming content'
purpose:
  - type: internal
    label: Contact
    item: da772011-5421-4bf1-ae33-d8c6e2ac2315
  - type: internal
    label: Evacrity introduction
    item: 6e6bdbf1-3575-40e6-bbd9-6080d00a013b
